const postAction = {
  LOAD_POST: "LOAD_POST",
  LOAD_POST_SUCCESS: "LOAD_POST_SUCCESS",
  LOAD_POST_ERROR: "LOAD_POST_ERROR",

  LOAD_POST_SAVE: "LOAD_POST_SAVE",
  LOAD_POST_SAVE_SUCCESS: "LOAD_POST_SAVE_SUCCESS",
  LOAD_POST_SAVE_ERROR: "LOAD_POST_SAVE_ERROR",

  DELETE_POST: "DELETE_POST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_ERROR: "DELETE_POST_ERROR",

  UPDATE_POST: "UPDATE_POST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_ERROR: "UPDATE_POST_ERROR",
}

export { postAction }
